version: '2.4'
x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/customerportal?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root

services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - ghmc_data:/var/lib/mysql
    mem_limit: 512m

  merchants:
    image: gustavohmcaldas/merchants:0.0.1-SNAPSHOT
    ports:
    - "8081:8081"
    environment:
      <<: *database-variables
    mem_limit: 512m

  merchants-frontend:
    image: gustavohmcaldas/merchants-frontend:latest
    ports:
    - "4200:80"
    mem_limit: 512m

volumes:
  ghmc_data: