spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/customerportal?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
#    username: root
    url: jdbc:postgresql://ec2-54-166-192-244.compute-1.amazonaws.com:5432/dc3399n44547rj?createDatabaseIfNotExist=true
    username: wfxdisscjnxcds
    password: e06056eeef5efe2181d21cbcd2e0d8ec06b6ae2084d348254ab4d66222bbbd6e
    
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true