spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/customerportal?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
#    username: root
    url: jdbc:postgresql://localhost:5432/codechallenge?createDatabaseIfNotExist=true
    username: postgres
    password: 123456
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true